name: Deploy master preview
on:
  push:
    branches:
      - master

jobs:
  test-and-release:
    name: Deploy preview to Surge
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn ci
      - name: Build in mock mode
        run: yarn build:mock
      - name: Install Surge
        run: npm install -g surge
      - name: Deploy to Surge
        run: surge ./dist/ konveyor-forklift-ui-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
