name: PR Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Yarn ci
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Generate yarn.lock
        run: yarn import
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn ci
